backend:
  name: github
  repo: dendesoft/kwidoo-travel
  branch: main
  client_id: Ov23li5zTwBk6cHHlQY2
  base_url: https://kwidoo-travel.pages.dev

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
